### ISSUE TITLE
free() invalid pointer when using UpROOT PythonPlot

### ISSUE THREAD

**Issue by alusiani** [stevengj/PythonPlot.jl#16]
The following minimum example code

```
using UpROOT
using PythonPlot
```

fails with:

```
free(): invalid pointer
signal (6): Aborted
```

Julia 1.7.3
UpROOT v0.3.3
PythonPlot v1.0.0

I guess it should be related to both packages calling Python.

**Comment by stevengj** [comment]
UpROOT.jl uses PyCall.  This is incompatible with PythonCall.   You should use it with PyPlot, not PythonPlot.

**Comment by alusiani** [comment]
The fault comes from an incompatibility between PyCall and PythonCall, which can be fixed by getting:
```
ENV["JULIA_PYTHONCALL_EXE"] = "@PyCall"
```
see [PythonCall Tips](https://cjdoris.github.io/PythonCall.jl/stable/pycall/#Tips).
