### ISSUE TITLE
Is `PyAny` defined in PythonCall.jl?

### ISSUE THREAD

**Issue by singularitti** [stevengj/PythonPlot.jl#19]
Hi, when I was reading your code, I found [this line](https://github.com/stevengj/PythonPlot.jl/blob/08cc7e384bea31b36eb2cc26e01b951a66cc9c61/src/PythonPlot.jl#L71) includes type `PyAny`, which seems to be defined only in PyCall, but not PythonCall:

```julia
(f::Figure)(args...; kws...) = pycall(Py(f), PyAny, args...; kws...)
```

Could it be a typo?

**Comment by stevengj** [comment]
I think this is leftover from the PyPlot/PyCall conversion.

I'm actually not sure why we have this method at all.  Are Matplotlib figure objects callable?

**Comment by stevengj** [comment]
Hmm, it stems from https://github.com/JuliaPy/PyPlot.jl/commit/62ff118487c942bbd9b1f38b712981736650d7e6 …

**Comment by stevengj** [comment]
Comes from [this post on julia-users](https://groups.google.com/g/julia-users/c/ux48rIR7UsU/m/01p7TGTvkEMJ).  Looks like `ColorMap` objects should be callable, and I added it to `Figure` for good measure.

**Comment by stevengj** [comment]
Nope, it's not callable.  I get:
```
ERROR: Python: TypeError: 'Figure' object is not callable
```
so I should probably just delete this method.

**Comment by stevengj** [comment]
ColorMap is already okay: https://github.com/stevengj/PythonPlot.jl/blob/08cc7e384bea31b36eb2cc26e01b951a66cc9c61/src/colormaps.jl#L19-L20
