### ISSUE TITLE
set_yticks( [ ] ); Failed to convert value(s) to axis units 

### ISSUE THREAD

**Issue by mdhe1248** [stevengj/PythonPlot.jl#36]
How can I remove all ticks? The help doc says, 
  Pass an empty list to remove all ticks::
  set_yticks([])

This used to work with PyPlot.jl (although I have not tried it after some system update), but with PythonPlot, i am getting the following error: 
ERROR: Python: ConversionError: Failed to convert value(s) to axis units: Julia: Any[]

Thank you in advance!

**Comment by stevengj** [comment]
Apparently Matplotlib doesn't like PythonCall's wrapper for a Julia empty `Any` array.   Either of the following seem to work:
```py
ax.set_yticks(Int[]) # use a typed empty array — numpy knows how to convert this
ax.set_yticks(pylist()) # use a native Python empty list
```

**Comment by stevengj** [comment]
See https://github.com/JuliaPy/PythonCall.jl/issues/486 — PythonCall converts `[] == Any[]` into something like a numpy array of `object`, which is treated quite differently in numpy than a Python `list`.
