### ISSUE TITLE
3D plots/subplots

### ISSUE THREAD

**Issue by PaulSoderlind** [stevengj/PythonPlot.jl#4]
Just to have it recorded: 
https://github.com/JuliaPy/PyPlot.jl/issues/532#issuecomment-936126035 
applies to PythonPlot.jl too

Otherwise, some experimenting suggests that PythonPlot.jl works very nicely. It's a bit picky about the *backends* (have not yet managed to get qt5 working, although I don't have problems with that on PyPlot.jl)

**Comment by stevengj** [comment]
Please open a separate issue about the qt5 backend.  (Note that PyPlot.jl automatically installs pyqt5 for you if you want this backend, whereas PythonPlot does not.)
