### ISSUE TITLE
Default :tk pygui makes julia registry segfault

### ISSUE THREAD

**Issue by mloubout** [stevengj/PythonPlot.jl#42]
I've spent a few days trying to figure out what's wrong without success, but it looks like the default PythonPlot backend (:tk) is making import segfault at least in julia automerge CI:

https://github.com/JuliaRegistries/General/actions/runs/11556341068/job/32163801717?pr=117989#step:17:863

I wanted to change the default backend but from the look of it [here](https://github.com/JuliaPy/PythonPlot.jl?tab=readme-ov-file#choosing-a-python-gui-toolkit) it would need PyCall which defeat the purpose of using PythonPlot in the first place.

If the backend could be handled via preferences or environment variable so that it can be set before PythonCall is imported it would be quite helpful.

**Comment by stevengj** [comment]
Sorry, the instructions were mis-copied over from PyPlot.jl … you don't use PyCall for this.  Just set the MPLBACKEND environment variable.  

Fixed in 93dfb2ec07ce1b7f4e3e26676f17aa5202e953ad
